spring:
  application:
    name: gate
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true
  flyway:
    enabled: true
    locations:
      - classpath:db/migration

brevo:
  api-key: ${BREVO_API_KEY}
  base-url: ${BREVO_API_BASE_URL}
  sender:
    name: ${BREVO_DEFAULT_SENDER_NAME}
    email: ${BREVO_DEFAULT_SENDER_EMAIL}

ratelimit:
  default:
    capacity: 10
    refill: 1m