volumes:
  postgres-gate-data:
  rabbitmq-gate-data:
  shell-history:

networks:
  gate-network:
    driver: bridge

services:
  app:
    container_name: cartumio-gate-app
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
        POSTGRES_PASSWORD: cartumio_password
        POSTGRES_USER: cartumio_user
        POSTGRES_DB: cartumio_gate
        POSTGRES_HOSTNAME: postgresdb
    volumes:
      - ../..:/workspaces:cached
      - shell-history:/dc/shellhistory
    command: sleep infinity
    networks:
      - gate-network

  postgres:
    container_name: postgres-cartumio-gate
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-gate-data:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: cartumio_password
        POSTGRES_USER: cartumio_user
        POSTGRES_DB: cartumio_gate
    networks:
      - gate-network

  rabbitmq:
    container_name: rabbitmq-cartumio-gate
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    volumes:
      - rabbitmq-gate-data:/var/lib/rabbitmq/data
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - gate-network