volumes:
  postgres-gate-data:
  rabbitmq-gate-data:
  shell-history:

networks:
  gate-network:
    driver: bridge

services:
  app:
    container_name: cartumio-gate-app
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ../..:/workspaces:cached
      - shell-history:/dc/shellhistory
    command: sleep infinity
    ports:
      - "8080:8080"
    networks:
      - gate-network
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    container_name: postgres-cartumio-gate
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-gate-data:/var/lib/postgresql
    env_file:
      - .env
    networks:
      - gate-network
    ports:
      - "${POSTGRES_PORT}:5432"

  rabbitmq:
    container_name: rabbitmq-cartumio-gate
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    volumes:
      - rabbitmq-gate-data:/var/lib/rabbitmq
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - gate-network
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"